// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Server.Models
{
    public partial class DepartmentBudgetsSINGLEResult
    {
        public int DepartmentId { get; set; }
        public decimal? BudgetAmount { get; set; }
        public decimal? ActualBudgetAmount { get; set; }
        public decimal? Q1 { get; set; }
        public decimal? Q2 { get; set; }
        public decimal? Q3 { get; set; }
        public decimal? Q4 { get; set; }
        public decimal? PercentegaScore { get; set; }
        public string Year { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public bool? IsDeleted { get; set; }
        public bool? IsCurrent { get; set; }
        public decimal? GM { get; set; }
        public int? Month { get; set; }
        public string Date { get; set; }
    }
}
