// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Server.Models
{
    public partial class EmployeeIncentiveMonthliesSINGLEResult
    {
        public int Id { get; set; }
        public int? EmployeeId { get; set; }
        public int? DepartmentId { get; set; }
        public string DeptName { get; set; }
        public decimal ExpectedPIPPayable { get; set; }
        public decimal ActualPIPPayable { get; set; }
        public decimal MDPenalty { get; set; }
        public int PercentageScore { get; set; }
        public DateTime? Month { get; set; }
        public string FirstAuthorizer { get; set; }
        public string SecondAuthorizer { get; set; }
        public string ThirdAuthorizer { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
    }
}
